// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt248s9EF5UtD3pTn9vnRphIkly5q1FFg',
    appId: '1:319791497075:android:7a64b464e76e3f06304f06',
    messagingSenderId: '319791497075',
    projectId: 'zoom-clone-b8cb7',
    storageBucket: 'zoom-clone-b8cb7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZvPRVUHPtrOHF3gp72xEfVHNnp6q8nTE',
    appId: '1:319791497075:ios:ac9b1a46363eacb0304f06',
    messagingSenderId: '319791497075',
    projectId: 'zoom-clone-b8cb7',
    storageBucket: 'zoom-clone-b8cb7.appspot.com',
    androidClientId: '319791497075-qcgcfgb548gquqda84emjf5shej7mlj6.apps.googleusercontent.com',
    iosClientId: '319791497075-c7p7b7fe9vod1i2dmbma5i8j1rt7mdv0.apps.googleusercontent.com',
    iosBundleId: 'com.example.zoomClone',
  );
}
